server:
  contextPath: /swagger2-demo
  port: 8085
spring:
  boot:
  application:
    name: audit-consumer
  zipkin:
    enabled: false
  sleuth:
    async:
      configurer:
        enabled: true
  kafka:
    bootstrap-servers: kafka:9092
    template:
      default-topic: bmi_audit
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: kafka:9092
      group-id: bmi_audit_consumer_group
      auto-offset-reset: earliest
      auto-commit-interval: 100
      enable-auto-commit: false
      isolation-level: read_committed
      properties:
        max:
          poll:
            interval:
              ms: 5000
management:
  endpoint:
    health:
      status:
        order: fatal,down,out-of-service,unknown,up
        http-mapping:
          fatal: 503
          down: 503
          out-of-service: 503
    beans:
      cache:
        time-to-live: 10s
    shutdown:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      slo:
        http:
          server:
            requests: 1s,5s,30s
    enable:
      tomcat: false
      process: false
      system: false
      jdbc: false
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric,env,httptrace,loggers
        exclude: env,beans
    enabled-by-default: true
  health:
    status:
      order: fatal,down,out-of-service,unknown,up
    show-details: always

logging:
  level:
    root: INFO
  file:
    name: ./logs/audit-consumer.log
    path: ./logs
  logback:
    rollingpolicy:
      max-file-size: 20MB
      file-name-pattern: .logs/audit-consumer-%d{yyyy-MM-dd}.%i.log

secretKeyLocation: /opt/configs

sso:
  grant-type: client_credentials
  scopes: transaction
  authorization: Basic a2V5OnNlY3JldA==

advertised:
  host:
    name: kafka1
listeners: SASL_PLAINTEXT://kafka1:9092
delete:
  topic:
    enable: true

security.inter.broker.protocol: SASL_PLAINTEXT
sasl:
  mechanism:
    inter:
      broker:
        protocol: PLAIN


audit:
  server:
    request:
      url: http://log1:9080/audit/audit/request
    response :
      url: http://log1:9080/audit/audit/response
    methodCall:
      url: http://log1:9080/audit/audit/methodCall

session:
  timeout:
    ms: 15000

bmi:
  oauth2:
    excluded-urls: /api/agreements/audit,/v3/api-docs/**,/swagger-ui/**:*,/h2/**:*,/swagger-ui.html:*,/webjars/**:*,/v2/**:*,/swagger-resources/**:*,/actuator/**:*,/actuator/prometheus/**:*,/trace/**:*,/enterprisebaamapi/h2/**:*,/enterprisebaamapi/swagger-ui.html:*,/enterprisebaamapi/webjars/**:*,/enterprisebaamapi/v2/**:*,/enterprisebaamapi/swagger-resources/**:*,/enterprisebaamapi/actuator/**:*,/enterprisebaamapi/actuator/prometheus/**:*,/enterprisebaamapi/trace/**:*,/applications/**
