apiVersion: v1
kind: Service
metadata:
  name: audit-consumer
  labels:
    app: audit-consumer
spec:
  selector:
    app: audit-consumer
  ports:
    - name: "http"
      port: 8585
      targetPort: 8585
  type: NodePort